dist: xenial
sudo: required
services: 
  - docker

language: bash

jobs:
  include:

    # Run main e2e tests
    - stage: test
      name: "Main e2e tests"
      script:
        - ./scripts/testing.sh
        - ./scripts/oc-cluster.sh
        - oc login -u developer
        - cd $GOPATH/src/github.com/openshift/odo
        - make bin
        - sudo cp odo /usr/bin/odo
        - make test-main-e2e

    # Run component e2e tests
    - stage: test
      name: "Component e2e tests"
      script:
        - ./scripts/testing.sh
        - ./scripts/oc-cluster.sh
        - oc login -u developer
        - cd $GOPATH/src/github.com/openshift/odo
        - make bin
        - sudo cp odo /usr/bin/odo
        - travis_wait make test-cmp-e2e

    # Run java e2e tests
    - stage: test
      name: "Java e2e tests"
      script:
        - ./scripts/testing.sh
        - ./scripts/oc-cluster.sh
        - oc login -u developer
        - cd $GOPATH/src/github.com/openshift/odo
        - make bin
        - sudo cp odo /usr/bin/odo
        - make test-java-e2e

    # Run source e2e tests
    - stage: test
      name: "Source e2e tests"
      script:
        - ./scripts/testing.sh
        - ./scripts/oc-cluster.sh
        - oc login -u developer
        - cd $GOPATH/src/github.com/openshift/odo
        - make bin
        - sudo cp odo /usr/bin/odo
        - make test-source-e2e

    # Run service-catalog e2e tests
    - stage: test
      name: "Service-Catalog e2e tests"
      script:
        - ./scripts/testing.sh
        - ./scripts/oc-cluster.sh service-catalog
        - oc login -u developer
        - cd $GOPATH/src/github.com/openshift/odo
        - make bin
        - sudo cp odo /usr/bin/odo
        - make test-service-e2e
